"""
Domain models for MCP-1C.

Contains Pydantic models representing 1C:Enterprise metadata objects.
"""

from mcp_1c.domain.metadata import (
    Attribute,
    Form,
    MetadataObject,
    MetadataType,
    Module,
    ModuleType,
    Subsystem,
    TabularSection,
    Template,
)
from mcp_1c.domain.code import (
    BslModule,
    CodeLocation,
    CodeReference,
    CompilationDirective,
    DependencyEdge,
    DependencyGraph,
    ExtendedBslModule,
    MetadataReference,
    MetadataReferenceType,
    MethodCall,
    Parameter,
    Procedure,
    QueryReference,
    Region,
    VariableUsage,
)
from mcp_1c.domain.templates import (
    CodeTemplate,
    GenerationContext,
    GenerationResult,
    ParsedQuery,
    Placeholder,
    PlaceholderType,
    QueryCondition,
    QueryField,
    QueryOptimizationSuggestion,
    QueryTableReference,
    QueryValidationResult,
    TemplateCategory,
    TemplateExample,
    TemplateSuggestion,
)
from mcp_1c.domain.mxl import (
    AreaType,
    BorderStyle,
    CellAlignment,
    CellBorders,
    CellStyle,
    CellType,
    CellVerticalAlignment,
    FillCodeGenerationOptions,
    GeneratedFillCode,
    MxlArea,
    MxlCell,
    MxlDocument,
    MxlParseResult,
    ParameterType,
    TemplateParameter,
)

from mcp_1c.domain.embedding import (
    EmbeddingDocument,
    EmbeddingStats,
    SearchResult,
)

__all__ = [
    # Metadata models
    "MetadataType",
    "MetadataObject",
    "Attribute",
    "TabularSection",
    "Form",
    "Template",
    "Module",
    "ModuleType",
    "Subsystem",
    # Code models (Phase 1)
    "BslModule",
    "Procedure",
    "Parameter",
    "CompilationDirective",
    "Region",
    "CodeLocation",
    "CodeReference",
    # Code models (Phase 2)
    "ExtendedBslModule",
    "MethodCall",
    "MetadataReference",
    "MetadataReferenceType",
    "VariableUsage",
    "QueryReference",
    "DependencyEdge",
    "DependencyGraph",
    # Template models (Phase 3)
    "CodeTemplate",
    "TemplateCategory",
    "PlaceholderType",
    "Placeholder",
    "TemplateExample",
    "GenerationContext",
    "GenerationResult",
    "TemplateSuggestion",
    "QueryTableReference",
    "QueryField",
    "QueryCondition",
    "ParsedQuery",
    "QueryValidationResult",
    "QueryOptimizationSuggestion",
    # MXL models (Phase 4)
    "CellType",
    "AreaType",
    "CellAlignment",
    "CellVerticalAlignment",
    "BorderStyle",
    "ParameterType",
    "CellBorders",
    "CellStyle",
    "TemplateParameter",
    "MxlCell",
    "MxlArea",
    "MxlDocument",
    "MxlParseResult",
    "FillCodeGenerationOptions",
    "GeneratedFillCode",
    # Embedding models (Phase 6)
    "EmbeddingDocument",
    "EmbeddingStats",
    "SearchResult",
]
